# Site settings
title: Spray Bomb
email: webtastic.dc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Portfolio of Street Art From Around The World
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spray-bomb.com" # the base hostname & protocol for your site
twitter_username: darrellchaddock
github_username:  vanpixxer
behance_username: Vanpixxer

# Build settings
markdown: kramdown
